### PR TITLE
Encapsulate number libs

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
@emord I bumped the version. How do you then get it to recognize that version in package.json? By creating a tag?

**Comment by emord** [comment]
I think you can do a tag. 

may want to start publishing it on npm/bower https://docs.npmjs.com/getting-started/publishing-npm-packages although js-xpath isn't a great name for this. maybe just xpath-parser? (xpath libraries on npm usually means that it actually executes xpath)

Publishing on npm means we can start using

```
{
  "xpath-parser": "0.0.2"
}
```

**Comment by dannyroberts** [comment]
ok, for now I've made the tag v0.0.2-rc1 (I'm being tedious, but I did that because tests haven't passed here yet.) Can I let you decide when/how you want to publish this to npm/bower? (Might have to think about the process of doing both if we go down that route.)

**Comment by dannyroberts** [comment]
:white_check_mark:

**Pull request merged**
