### PR TITLE
Keep parens

### PR DESCRIPTION
**Pull request by emord**
http://manage.dimagi.com/default.asp?230222

As a side effect of transforming /data/ -> #form and instance('casedb') -> #case js-xpath removes parenthesis that aren't necessary, but that makes some xpaths much harder to read

cc @NoahCarnahan 

@orangejenny @millerdev possibly interested

### CODE REVIEW

**Comment by emord** [comment]
This is still somewhat lossy. `(/data/question)` would still lose parenthesis, but I don't think that's a big deal.

**Comment by millerdev** [comment]
Can you give an example of an xpath that is easier to read with extra parens?

**Comment by emord** [comment]
from the ticket:

`(a > 3) or (b < 4 and c > 5) or (d = 5 and f = 2)`

would be changed to

`a> 3 or b < 4 and c > 5 or d=5 and f = 2`

**Comment by millerdev** [comment]
Hmm, so it seems like this will work, but it's changing a thing in the parser that has always worked in the past so it makes me a little nervous to change it now. Is the problem that when migrating a form to the new case management that expressions are run through the parser, which strips extra parens?

Will loss of parens ever happen after the form is migrated? Seems like it should not since we should always preserve exactly what the user typed in the expression, including all white space, which the parser will certainly not do.

A possibly better solution (for converting expressions during migrating only) would be to find all things that can be converted to hashtags in the expression and only replace them, preserving everything else the user typed including whitespace and extra parens. This may not be a trivial solution, but seems better since it would preserve more of what the user originally typed.

**Comment by emord** [comment]
> Will loss of parens ever happen after the form is migrated? Seems like it should not since we should always preserve exactly what the user typed in the expression, including all white space, which the parser certainly will not do

Currently this will happen since we want to always change whatever they typed into hashtag syntax in case they paste in from an old form, use /data/ because that's what they're used to, etc

>A possibly better solution (for converting expressions during migrating only) would be to find all things that can be converted to hashtags in the expression and only replace them, preserving everything else the user typed including whitespace and extra parens. This may not be a trivial solution, but seems better since it would preserve more of what the user originally typed.

Agreed it would be better, but also much harder. Not sure if you suggest doing this inside or outside of this parser. It would probably be easiest to do it inside the parser and make the different forms of whitespace significant which seems strange to me.

**Comment by millerdev** [comment]
> Currently this will happen since we want to always change whatever they typed into hashtag syntax in case they paste in from an old form, use /data/ because that's what they're used to, etc

Does this mean that significant whitespace in expressions is always lost? If so we should probably create a parsing mode that preserves exactly what the user typed except for things that are converted to a hashtag.

> Not sure if you suggest doing this inside or outside of this parser.

To do it correctly we have to use a parser.

**Comment by emord** [comment]
The only significant whitespace should be inside a string, which would be
preserved. Are there any other cases where whitespace changes the behavior
of an xpath?

**Comment by millerdev** [comment]
Whitespace does not change the behavior, but people use it to make expressions easier to read (like the example above with parens). I think it's pretty critical that we preserve that.

**Pull request merged**
